// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_EXAM.Migrations
{
    [DbContext(typeof(EXAMDbContext))]
    [Migration("20230929222250_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_EXAM.Domain.Models.EXAMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EXAM_DATE");

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("LESSON_ID");

                    b.Property<int?>("Point")
                        .HasColumnType("int")
                        .HasColumnName("POINT");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("EXAMS");
                });

            modelBuilder.Entity("API_EXAM.Domain.Models.LESSONS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Class")
                        .HasColumnType("int")
                        .HasColumnName("CLASS");

                    b.Property<string>("InstructorName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("INSTRUCTOR_NAME");

                    b.Property<string>("InstructorSurname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("INSTRUCTOR_SURNAME");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("LESSONS");
                });

            modelBuilder.Entity("API_EXAM.Domain.Models.STUDENTS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Class")
                        .HasColumnType("int")
                        .HasColumnName("CLASS");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id");

                    b.ToTable("STUDENTS");
                });

            modelBuilder.Entity("API_EXAM.Domain.Models.EXAMS", b =>
                {
                    b.HasOne("API_EXAM.Domain.Models.LESSONS", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_EXAM.Domain.Models.STUDENTS", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
